export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/ResearcherryCoderInc/researcherry",
	GITHUB_DISCUSSIONS: "https://github.com/ResearcherryCoderInc/researcherry/discussions",
	DISCORD: "https://discord.gg/researcherry",
	REDDIT: "https://reddit.com/r/ResearcherryCoder",
	X: "https://x.com/researcherry_coder",
	LINKEDIN: "https://www.linkedin.com/company/researcherry",
	TIKTOK: "https://www.tiktok.com/@researcherry.coder",
	BLUESKY: "https://bsky.app/profile/researcherry.bsky.social",
	YOUTUBE: "https://www.youtube.com/@ResearcherryCoderYT",
	DOCUMENTATION: "https://docs.researcherry.com",
	CAREERS: "https://careers.researcherry.com",
	ISSUES: "https://github.com/ResearcherryCoderInc/researcherry/issues",
	FEATURE_REQUESTS: "https://github.com/ResearcherryCoderInc/researcherry/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/ResearcherryCoderInc/researcherry/discussions",
	CHANGELOG: "https://github.com/ResearcherryCoderInc/researcherry/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/ResearcherryCoderInc/researcherry/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.researcherry.com/community",
	TUTORIALS: "https://docs.researcherry.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=ResearcherryCoderInc.researcherry",
	SECURITY: "https://trust.researcherry.com",
	EVALS: "https://researcherry.com/evals",
	BLOG: "https://blog.researcherry.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@ResearcherryCoderYT/podcasts",
	FAQ: "https://researcherry.com/#faq",
	TESTIMONIALS: "https://researcherry.com/#testimonials",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
