name: Release VSIX

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.2
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build VSIX
        run: pnpm -C src vsix

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: researcherry-vsix
          path: bin/*.vsix

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.VSCE_PAT && secrets.OVSX_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.2
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build VSIX
        run: pnpm -C src vsix

      - name: Publish to Marketplace and OpenVSX
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: pnpm -C src publish:marketplace


